print("BOLETA N°4")
#INPUT
nombre_cine=input("Nombre del cine es: ")
R_U_C=int(input("El numero de R.U.C es:"))
caja=int(input("El numero de caja es: "))
cajera=input("El nombre de la cajera es: ")
fecha=input("ingrese la fecha: ")
hora=input("ingrese la hora:")
cliente=input("El nombre del cliente es:")
nombre_pelicula=input("El nombre de la pelicula es: ")
n_sala=int(input("El numero de sala es: "))
costo_pelicula=float(input("El precio de la pelicula es: "))
costo_combo_cine=float(input("El costo del combo de cine es: "))
#PROCESSING
gasto_total=(costo_combo_cine + costo_pelicula)
print("                                                      ")
#OUTPUT
print("#####################" + " " + nombre_cine +" ######################")
print("###########################################")
print("R.U.C  " + str(R_U_C))
print("cliente  " + cliente + "   caja  " + str(caja) + "  cajera  " + cajera)
print("################BOLETA DE VENTA#####################")
print("pelicula: " + nombre_pelicula + "     N° sala  " +  str(n_sala))
print("Descripcion     "  +  "  precio   " )
print("pelicula    " + "        " + str(costo_pelicula))
print("combo             "  + str(costo_combo_cine))
print("TOTAL................ " + str(gasto_total))
print("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _")
print("fecha de emision:" + str(fecha)    + "     hora:" + str(hora))

