print("BOLETA N°2")
#INPUT
empresa=input("Nombre de la empresa es: ")
R_U_C=int(input("El numero de R.U.C es:"))
caja=int(input("El numero de caja es: "))
fecha=input("ingrese la fecha: ")
hora=input("ingrese la hora:")
cajera=input("El nombre de la cajera es: ")
cliente=input("El nombre del cliente es:")
pantalon=int(input("Cantidad de pantalones: "))
costo_pantalon=float(input("El costo del pantalon por unidad es: "))
polo=int(input("El n° de polos: "))
costo_polo=float(input("El precio por unidad del polo es: "))
zapatos=int(input("El numero de zapatos comprados: "))
costo_zapatos=float(input("El costo de los zapatos por unidad es: "))

#PROCESSING
total_pantalon=(pantalon* costo_pantalon)
total_polo=(polo * costo_polo)
total_zapatos=(zapatos * costo_zapatos)
total_consumo=(total_pantalon + total_polo + total_zapatos)
print("                                                      ")
#OUTPUT
print("##################### METRO ######################")
print("############## CENCOSUD RETAIL PERU S.A##############")
print("                calle av.grau nro 589")
print("R.U.C  " + str(R_U_C))
print("cliente  " + cliente + "   caja  " + str(caja) + "  cajera  " + cajera)
print("################BOLETA DE VENTA#####################")
print("                                            ")
print("producto     " + "    cantidad    " +  "   precio   " +   "    total")
print("pantalon     " + "       " + str(pantalon)  +   "            "  +   str(costo_pantalon)  + "         "  +  str(total_pantalon))
print("polo                "  + str(polo) + "            " + str(costo_polo) + "        " + str(total_polo))
print("zapatos             "  + str(zapatos)   + "            "  + str(costo_zapatos) + "         " + str(total_zapatos))
print("monto total:            s/   " + str(total_consumo))
print("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _")
print("fecha de emision:" + str(fecha)    + "     hora:" + str(hora))
print("              gracias por su compra en " + empresa)
