print("BOLETA N°3")
#INPUT
empresa=input("Nombre de la empresa es: ")
R_U_C=int(input("El numero de R.U.C es:"))
caja=int(input("El numero de caja es: "))
fecha=input("ingrese la fecha: ")
hora=input("ingrese la hora:")
cajera=input("El nombre de la cajera es: ")
cliente=input("El nombre del cliente es:")
pack_sodaV=int(input("Cantidad six pack de de soda V: "))
costo_sodaV=float(input("El costo del six pack de soda V es: "))
gomitas=int(input("La cantidad de gomitas: "))
costo_gomitas=float(input("El precio de las gomita es: "))
frugos_durazno=int(input("El numero de frugos de durazno: "))
costo_frugos=float(input("El costo de los frugos por el pack es: "))

#PROCESSING
total_pack_SodaV=(pack_sodaV* costo_sodaV)
total_gomitas=(gomitas * costo_gomitas)
total_frugos=(frugos_durazno * costo_frugos)
total_consumo=(total_pack_SodaV + total_gomitas + total_frugos)
print("                                                      ")
#OUTPUT
print("#####################" + " " + empresa +" ######################")
print("################# PLAZA VEA PERU S.A#################")
print("                calle bolognesi")
print("R.U.C  " + str(R_U_C))
print("cliente  " + cliente + "   caja  " + str(caja) + "  cajera  " + cajera)
print("################BOLETA DE VENTA#####################")
print("                                            ")
print("producto     " + "    cantidad    " +  "   precio   " +   "    total")
print("Soda V     " + "          " + str(pack_sodaV)  +   "            "  +   str(costo_sodaV)  + "         "  +  str(total_pack_SodaV))
print("Gomitas              "  + str(gomitas) + "           " + str(costo_gomitas) + "         " + str(total_gomitas))
print("Frugos               "  + str(frugos_durazno)   + "            "  + str(costo_frugos) + "          " + str(total_frugos))
print("monto total:            s/   " + str(total_consumo))
print("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _")
print("fecha de emision:" + str(fecha)    + "     hora:" + str(hora))
print("              gracias por su compra en " )
